version: "3.7"

x-deploy-data:
  envSchema:
    required:
      - CONFIG
    properties:
      CONFIG:
        type: string
        format: code/yaml
        description: The config used
        default: |
          some: yaml code
          to:
            test: if
            this: works
      SOME_URL_THAT_BEGIN_WITH_HTTP:
        type: string
        description: The url to connect the database, it will be kept encrypted
        pattern: ^http:\/\/$$

services:
  dummy-express:
    image: gcr.io/containerful/example-containerful-template
    build: .
    ports:
      - 1945:80
    environment:
      - SOME_URL_THAT_BEGIN_WITH_HTTP=${SOME_URL_THAT_BEGIN_WITH_HTTP}
      - CONFIG=${CONFIG}
